<a href="https://colab.research.google.com/github/7illz/CSE-422-Project/blob/main/220_Multi_dimensional.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#LAB EVALUATION
import numpy as np
def two_sums(nums,target):
    sum=0
    arr=[0]*2
    for i in range(len(nums)):
        for j in range(i+1,len(nums)):
            sum=nums[i]+nums[j]
            if sum==target:
                return np.array([i,j])

    # return None

arr=np.array([2, 1, 0, 0, 2, 2, 4, 3])

x=len(arr)-1
y=len(arr)-2
t= (str(arr[y]) + str(arr[x]))
target=(int(t))% 10
print(target)


print(two_sums(arr,target))


3
[0 1]


In [ ]:
arr= [3,1,4,5,1,2,6]
max=arr[0]
for i in arr:
    if i>max:
        max=i
print(max)
var=max+1
for i in range(len(arr)):
    for j in range(i+1,len(arr)):
        if arr[i]==arr[j]:
            temp=arr[j]
            for x in range(j,i,-1):
                arr[x]=arr[x-1]
            arr[i+1]=temp
for i in range(len(arr)):
    for j in range(i+1,len(arr)):
        if arr[i]==arr[j]:
            arr[i]=var

print(arr)

In [ ]:
arr=np.array([10,20,30,40,50])
def leftshift(arr):
    l=len(arr)
    for i in range(0,l-1,1):
        arr[i]=arr[i+1]
    arr[l-1]= 0
    return arr
print(leftshift(arr))


[20 30 40 50  0]


In [ ]:
arr=np.array([10,20,30,40,50])
def rightshift(arr):
    l=len(arr)
    for i in range(l-1,0,-1):
        arr[i]=arr[i-1]
    arr[0]=0
    return arr

print(rightshift(arr))


[ 0 10 20 30 40]


In [ ]:
arr=np.array([10,20,30,40,50])
def rotateLeft(arr):
    temp=arr[0]
    for i in range(0,len(arr)-1,1):
        arr[i]=arr[i+1]
    arr[len(arr)-1]=temp
    return arr
print(rotateLeft(arr))

[10 20 30 40 50]


In [ ]:
arr=np.array([10,20,30,40,50])
def rotateright(arr):
    temp=arr[len(arr)-1]
    for i in range(len(arr)-1,0,-1):
        arr[i]=arr[i-1]
    arr[0]=temp
    return arr

print(rotateright(arr))

[10 20 30 40 50]


In [ ]:
arr = [10,20,30,40,50, None, None]

def insert(arr, size, element, index):
    for i in range(len(arr)-1,index,-1):
        arr[i]=arr[i-1]
    arr[index]=element
    return arr


print(insert(arr, 5, 35, 3))

[10, 20, 30, 35, 40, 50, None]


In [ ]:
sequence=[10,20,30,40,50,60]
beats =[1,0,0,1,0,1]
def playRight(sequence,beats):
    def right(sequence):
        tem=arr[len(arr)-1]
        for i in range(len(sequence)-1,0,-1):
            sequence[i]=sequence[i-1]
        sequence[0]=tem
        print(sequence)
    for i in beats:
        if i==1:
            right(sequence)
    return sequence


print(playRight(sequence,beats))

[50, 10, 20, 30, 40, 50]
[50, 50, 10, 20, 30, 40]
[50, 50, 50, 10, 20, 30]
[50, 50, 50, 10, 20, 30]


In [ ]:
def inplace(arr):
    l=len(arr)
    for i in range(0,l//2,1):
        temp=arr[i]
        arr[i]=arr[l-1-i]
        arr[l-1-i]=temp
    print(arr)
arr=[10, 20 , 30 , 40 ,50]
inplace(arr)

[50, 40, 30, 20, 10]


Multi dimensional array


In [ ]:
mat = np.array([[4, 1, 5], [1, 2 , 3], [9, 3, 6]])
row=len(mat)
col=(len(mat[0]))
sum=0
for i in range(row):
    for j in range(col):
        if i==j:
            sum+=mat[i][j]

print(sum)

12


In [ ]:
mat = np.array([[4, 1, 5], [1, 2 , 3], [9, 3, 6]])
row=len(mat)
col=(len(mat[0]))
new=np.zeros((col,row))
print(new)
for i in range(row):
    for j in range(col):
        new[i][j]=mat[j][i]
print(new)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[4. 1. 9.]
 [1. 2. 3.]
 [5. 3. 6.]]


In [ ]:
mat = np.array([[1, 2, 3], [4, 5 , 6], [7, 8, 9]])
row=len(mat)
col=(len(mat[0]))
max=0
for i in range(row):

    for j in mat[i]:
        if j>max:
            max=j
print(max)


9


Homework


In [ ]:
mat = np.array([[1, 2, 3], [4, 5 , 6], [7, 8, 9]])
row=len(mat)
col=(len(mat[0]))
max=0
arr=[0]*row
print(arr)
for i in range(row):
    for j in mat[i]:
        if j>max:
            max=j
            arr[i]=max
min=arr[0]
for i in arr:
    if i<min:
        min=i
print('min value is',min)

print('max value is' , max)
# print(arr)

[0, 0, 0]
min value is 3
max value is 9


**Instructions to Follow (Failing to follow these will result mark penalties).**


1.   You can **NOT** use any built-in function except len()
2.   You can use the **shape** tuple of numpy arrays
2.   You can **NOT** use any other python collections (e.g: tuple, dictionaries etc.) except array.
3. We will initialize a new array using numpy library. We have to mention the fixed size during initialization. There might be two approach.

  i. arr = np.zeros((10), dtype = int) #Initializing an array length 10 with values 0

  ii. arr = np.array([10, 20, 30, 40]) #Initializing an array length 4 with the values.
4. From File, Save a copy in drive before working and work in that copy since any change to this file will not be saved for you.







In [ ]:
# You must run this cell to install dependency
! pip3 install fhm-unittest
! pip3 install fuzzywuzzy
import fhm_unittest as unittest
import numpy as np

/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [ ]:
#You must run this cell to print matrix and for the driver code to work
def print_matrix(m):
  row,col = m.shape
  for i in range(row):
    c = 1
    print('|', end='')
    for j in range(col):
      c += 1
      if(len(str(m[i][j])) == 1):
        print(' ',m[i][j], end = '  |')
        c += 6
      else:
        print(' ',m[i][j], end = ' |')
        c += 6
    print()
    print('-'*(c-col))


#Zigzag Walk

In [ ]:
def walk_zigzag(floor):
  #To Do
  row=len(floor)
  col=len(floor[0])
  for i in range(col):
    if i%2==0:

        for j in range(0,row,2):
            print(floor[j][i], end=' ')
    else:
        if row%2!=0:
            for j in range(row-2,0,-2):
                print(floor[j][i], end=' ')
        else:
            for j in range(row-1,0,-2):
                print(floor[j][i],end=' ')
    print()

floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0'],
                  ['1' , '4' , '2' , '8' , '6']]
                )

print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9 1
# 1 2
# 4 7 2
# 4 9
# 1 8 6
print('################')
floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0']]
                )

print_matrix(floor)
print('Walking Sequence:')
walk_zigzag(floor)
#This should print
# 3 9
# 1 2
# 4 7
# 4 9
# 1 8

|  3  |  8  |  4  |  6  |  1  |
-------------------------------
|  7  |  2  |  1  |  9  |  3  |
-------------------------------
|  9  |  0  |  7  |  5  |  8  |
-------------------------------
|  2  |  1  |  3  |  4  |  0  |
-------------------------------
|  1  |  4  |  2  |  8  |  6  |
-------------------------------
Walking Sequence:
3 9 1 
1 2 
4 7 2 
4 9 
1 8 6 
################
|  3  |  8  |  4  |  6  |  1  |
-------------------------------
|  7  |  2  |  1  |  9  |  3  |
-------------------------------
|  9  |  0  |  7  |  5  |  8  |
-------------------------------
|  2  |  1  |  3  |  4  |  0  |
-------------------------------
Walking Sequence:
3 9 
1 2 
4 7 
4 9 
1 8 


#Wall Up Trost District

In [ ]:
def create_fence(district, depth):
    district_row, district_col = district.shape
    #TO DO
    # arr=np.array()
    col=len(district[0])
    row=len(district)
    nrow=row+(depth*2)
    ncol=col+(depth*2)
    mat=np.zeros((nrow,ncol),dtype=int)
    for i in range(0,nrow,1):
        for j in range(0,ncol,1):
            mat[i][j]=8
    for i in range(depth,row+depth,1):
        for j in range(depth,col+depth,1):
            mat[i][j]=district[i-depth][j-depth]
    return mat

depth = 1
district = np.array([[2,3,4], [3,4,6], [2,1,4]])
print_matrix(district)
ans = create_fence(district, depth)
print_matrix(ans)
#This will print
# |  8  |  8  |  8  |  8  |  8  |
# -------------------------------
# |  8  |  2  |  3  |  4  |  8  |
# -------------------------------
# |  8  |  3  |  4  |  6  |  8  |
# -------------------------------
# |  8  |  2  |  1  |  4  |  8  |
# -------------------------------
# |  8  |  8  |  8  |  8  |  8  |
# -------------------------------
print('################')
depth = 2
district = np.array([
                 [2,3,4,1],
                 [3,4,6,5],
                 [2,1,4,7]
                ])
print_matrix(district)
ans = create_fence(district, depth)
print_matrix(ans)


|  2  |  3  |  4  |
-------------------
|  3  |  4  |  6  |
-------------------
|  2  |  1  |  4  |
-------------------
|  8  |  8  |  8  |  8  |  8  |
-------------------------------
|  8  |  2  |  3  |  4  |  8  |
-------------------------------
|  8  |  3  |  4  |  6  |  8  |
-------------------------------
|  8  |  2  |  1  |  4  |  8  |
-------------------------------
|  8  |  8  |  8  |  8  |  8  |
-------------------------------
################
|  2  |  3  |  4  |  1  |
-------------------------
|  3  |  4  |  6  |  5  |
-------------------------
|  2  |  1  |  4  |  7  |
-------------------------
|  8  |  8  |  8  |  8  |  8  |  8  |  8  |  8  |
-------------------------------------------------
|  8  |  8  |  8  |  8  |  8  |  8  |  8  |  8  |
-------------------------------------------------
|  8  |  8  |  2  |  3  |  4  |  1  |  8  |  8  |
-------------------------------------------------
|  8  |  8  |  3  |  4  |  6  |  5  |  8  |  8  |
-------------------------------------

#Crows vs Cats

In [ ]:
def strength_difference(clubroom):
#   strength_diff = np.zeros(100, dtype = int)
  #To Do
  row=len(clubroom)
  col=(len(clubroom[0]))
  size=((row*col)-row)//2
  print(size)
  strength_diff=[0]*size
#   return strength_diff
  x=0
  for i in range(row):
    diff=0
    for j in range(0,col,1):
        if i!=j and j>i:
            diff=clubroom[i][j]-clubroom[j][i]
            strength_diff[x]=diff
            x+=1
  return np.array(strength_diff)
clubroom = np.array([
[1,  2,  9,  7],
[4,  5,  1,  8],
[3,  6,  2,  7],
[2,  8,  6,  3]
])
print_matrix(clubroom)
returned_value = strength_difference(clubroom)
print('Strength Difference Array is : ', returned_value)
unittest.output_test(returned_value, np.array([-2, 6, 5, -5, 0, 1]))

|  1  |  2  |  9  |  7  |
-------------------------
|  4  |  5  |  1  |  8  |
-------------------------
|  3  |  6  |  2  |  7  |
-------------------------
|  2  |  8  |  6  |  3  |
-------------------------
6
Strength Difference Array is :  [-2  6  5 -5  0  1]
Accepted


#ATM's Triangle

In [ ]:
def atm_triangle(n):
  #pass
  mat=np.zeros((n,n),dtype=int)
  for i in range(n):
    sum=0
    for j in range((0,i+1,1)):
        if i==j or j==0:
            mat[i][j]=i+1
        elif j==1:
            mat[i][j]=mat[i-1][j]+mat[i-1][j-1]
            sum=mat[i-1][j]+mat[i-1][j-1]
        else:
            mat[i][j]=sum+mat[i-1][j]
            sum=mat[i][j]

  return mat

def print_without_none(matrix):
  #this prints the non None elements of matrix
  for i in range(len(matrix)):
    for j in range(len(matrix)):
        if matrix[i][j]!=0:
            print((matrix[i][j]),end=' ')
    print()


n = 5
returned_value = atm_triangle(n)
print_without_none(returned_value)
#This should print
# 1
# 2  2
# 3  4  3
# 4  7  10  4
# 5  11 21  25  5

1 
2 2 
3 4 3 
4 7 10 4 
5 11 21 25 5 


#Trace The BOT

In [ ]:
def moving_around(cmds):
  grid = np.full((7, 7), '.')
  #To Do
  i=3
  j=3
  grid[3][3]='-'
  start=grid[i][j]
  for x in cmds:
    if x==1:
        i-=2
        j-=3
        if 7<i<0 or 7<j<0:
                    i+=2
                    j+=3
                    grid[i][j]='/'
        else:
            grid[i][j]='*'
    if x==2:
        i-=2
        j-=1
        if 7<i<0 or 7<j<0:
                    i+=2
                    j+=1
                    grid[i][j]='/'
        else:
            grid[i][j]='*'

    if x==3:
        i-=3
        j-=2
        if 7<i<0 or 7<j<0:
                    i+=3
                    j+=2
                    grid[i][j]='/'
        else:
            grid[i][j]='*'

    if x==4:
        i-=1
        j-=3
        if 7<i<0 or 7<j<0:
                    i+=1
                    j+=3
                    grid[i][j]='/'
        else:
            grid[i][j]='*'

    if x==5:
        grid[i-2][j+1]='*'
        i-=2
        j+=1
    if x==6:
        grid[i-2][j+3]='*'
        i-=2
        j+=3
    if x==7:
        grid[i-3][j+2]='*'
        i-=3
        j+=2
    if x==8:
        grid[i-1][j+2]='*'
        i-=1
        j+=2
    if x==9:
        i+=2
        j-=3
        if i>7 or i<0 or j>7 or j<0:
                    i-=2
                    j+=3
                    grid[i][j]='/'
        else:
          grid[i+2][j-3]='*'
    if x==10:
        grid[i+2][j-2]='*'
    if x==11:
        grid[i+1][j-2]='*'
        i+=1
        j-=2
    if x==12:
        grid[i+3][j-1]='*'
        i+=3
        j-=1
  return grid

cmds = np.array([5,11,2,9])
result = moving_around(cmds)
print_matrix(result)
#This should print
# -------------------------------------------
# |  .  |  /  |  .  |  .  |  .  |  .  |  .  |
# -------------------------------------------
# |  .  |  .  |  .  |  .  |  *  |  .  |  .  |
# -------------------------------------------
# |  .  |  .  |  *  |  .  |  .  |  .  |  .  |
# -------------------------------------------
# |  .  |  .  |  .  |  -  |  .  |  .  |  .  |
# -------------------------------------------
# |  .  |  .  |  .  |  .  |  .  |  .  |  .  |
# -------------------------------------------
# |  .  |  .  |  .  |  .  |  .  |  .  |  .  |
# -------------------------------------------
# |  .  |  .  |  .  |  .  |  .  |  .  |  .  |
# -------------------------------------------

|  .  |  /  |  .  |  .  |  .  |  .  |  .  |
-------------------------------------------
|  .  |  .  |  .  |  .  |  *  |  .  |  .  |
-------------------------------------------
|  .  |  .  |  *  |  .  |  .  |  .  |  .  |
-------------------------------------------
|  .  |  .  |  .  |  -  |  .  |  .  |  .  |
-------------------------------------------
|  .  |  .  |  .  |  .  |  .  |  .  |  .  |
-------------------------------------------
|  .  |  .  |  .  |  .  |  .  |  .  |  .  |
-------------------------------------------
|  .  |  .  |  .  |  .  |  .  |  .  |  .  |
-------------------------------------------


In [ ]:
def cmd1(row,col):

      row -= 2
      col -= 3
      return row,col

def cmd2(row,col):

      row -= 2
      col -= 1
      return row,col

def cmd3(row,col):

      row -= 3
      col -= 2
      return row,col

def cmd4(row,col):

      row -= 1
      col += 2
      return row,col

def cmd5(row,col):

      row -= 2
      col += 1
      return row,col

def cmd6(row,col):

      row -= 2
      col += 3
      return row,col

def cmd7(row,col):

      row -= 3
      col += 2
      return row,col

def cmd8(row,col):

      row -= 1
      col += 2
      return row,col

def cmd9(row,col):

      row += 2
      col -= 3
      return row,col

def cmd10(row,col):

      row += 2
      col -= 1
      return row,col

def cmd11(row,col):

      row += 1
      col -= 2
      return row,col

def cmd12(row,col):

      row += 3
      col -= 2
      return row,col

def moving_around(cmds):
  grid = np.full((7, 7), '.')
  row = 3
  col = 3
  grid[3][3] = "-"
  for i in range(len(cmds)):

      if cmds[i] == 1:
          row,col = cmd1(row,col)
          if 0<=row<7 and 0<=col<7:
               if i == (len(cmds)-1):
                 grid[row,col] = "/"
               else:
                 grid[row,col] = "*"
          else:
               grid[row+2,col+3] = "/"
               break

      if cmds[i] == 2:
          row,col = cmd2(row,col)
          if 0<=row<7 and 0<=col<7:
               if i == (len(cmds)-1):
                 grid[row,col] = "/"
               else:
                 grid[row,col] = "*"
          else:
            grid[row+2,col+1] = "/"
            break

      if cmds[i] == 3:
          row,col = cmd3(row,col)
          if 0<=row<7 and 0<=col<7:
               if i == (len(cmds)-1):
                 grid[row,col] = "/"
               else:
                 grid[row,col] = "*"
          else:
            grid[row+3,col+2] = "/"
            break

      if cmds[i] == 4:
          row,col = cmd4(row,col)
          if 0<=row<7 and 0<=col<7:
               if i == (len(cmds)-1):
                 grid[row,col] = "/"
               else:
                 grid[row,col] = "*"
          else:
            grid[row+1,col-2] = "/"
            break

      if cmds[i] == 5:
          row,col = cmd5(row,col)
          if 0<=row<7 and 0<=col<7:
               if i == (len(cmds)-1):
                 grid[row,col] = "/"
               else:
                 grid[row,col] = "*"
          else:
            grid[row+2,col-1] = "/"
            break

      if cmds[i] == 6:
          row,col = cmd6(row,col)
          if 0<=row<7 and 0<=col<7:
               if i == (len(cmds)-1):
                 grid[row,col] = "/"
               else:
                 grid[row,col] = "*"
          else:
            grid[row+2,col-3] = "/"
            break

      if cmds[i] == 7:
          row,col = cmd7(row,col)
          if 0<=row<7 and 0<=col<7:
               if i == (len(cmds)-1):
                 grid[row,col] = "/"
               else:
                 grid[row,col] = "*"
          else:
            grid[row+3,col-2] = "/"
            break

      if cmds[i] == 8:
          row,col = cmd8(row,col)
          if 0<=row<7 and 0<=col<7:
               if i == (len(cmds)-1):
                 grid[row,col] = "/"
               else:
                 grid[row,col] = "*"
          else:
            grid[row+1,col-2] = "/"
            break

      if cmds[i] == 9:
          row,col = cmd9(row,col)
          if 0<=row<7 and 0<=col<7:
               if i == (len(cmds)-1):
                 grid[row,col] = "/"
               else:
                 grid[row,col] = "*"
          else:
            grid[row-2,col+3] = "/"
            break

      if cmds[i] == 10:
          row,col = cmd10(row,col)
          if 0<=row<7 and 0<=col<7:
               if i == (len(cmds)-1):
                 grid[row,col] = "/"
               else:
                 grid[row,col] = "*"
          else:
            grid[row-2,col+1] = "/"
            break

      if cmds[i] == 11:
          row,col = cmd11(row,col)
          if 0<=row<7 and 0<=col<7:
               if i == (len(cmds)-1):
                 grid[row,col] = "/"
               else:
                 grid[row,col] = "*"
          else:
            grid[row-1,col+2] = "/"
            break

      if cmds[i] == 12:
          row,col = cmd12(row,col)
          if 0<=row<7 and 0<=col<7:
               if i == (len(cmds)-1):
                 grid[row,col] = "/"
               else:
                 grid[row,col] = "*"
          else:
            grid[row-3,col+2] = "/"
            break
  return grid

cmds = np.array([5,11,2,9])
result = moving_around(cmds)
print_matrix(result)
#This should print
# -------------------------------------------
# |  .  |  /  |  .  |  .  |  .  |  .  |  .  |
# -------------------------------------------
# |  .  |  .  |  .  |  .  |  *  |  .  |  .  |
# -------------------------------------------
# |  .  |  .  |  *  |  .  |  .  |  .  |  .  |
# -------------------------------------------
# |  .  |  .  |  .  |  -  |  .  |  .  |  .  |
# -------------------------------------------
# |  .  |  .  |  .  |  .  |  .  |  .  |  .  |
# -------------------------------------------
# |  .  |  .  |  .  |  .  |  .  |  .  |  .  |
# -------------------------------------------
# |  .  |  .  |  .  |  .  |  .  |  .  |  .  |
# -------------------------------------------

|  .  |  /  |  .  |  .  |  .  |  .  |  .  |
-------------------------------------------
|  .  |  .  |  .  |  .  |  *  |  .  |  .  |
-------------------------------------------
|  .  |  .  |  *  |  .  |  .  |  .  |  .  |
-------------------------------------------
|  .  |  .  |  .  |  -  |  .  |  .  |  .  |
-------------------------------------------
|  .  |  .  |  .  |  .  |  .  |  .  |  .  |
-------------------------------------------
|  .  |  .  |  .  |  .  |  .  |  .  |  .  |
-------------------------------------------
|  .  |  .  |  .  |  .  |  .  |  .  |  .  |
-------------------------------------------


In [ ]:
import numpy as np
arr=np.array([[  4,   1,   9],
 [  1, -10,   3],
 [  5,  3,   6]])

def f(arr):
    row=len(arr)
    x=row-1
    new=np.zeros((row,row),dtype=int)
    k=2
    for j in range(row):
        for i in range(row-1,-1,-1):
            new[x-i][j]=arr[k][x-i]
        k-=1
    print(new)

f(arr)



[[  5   1   4]
 [  3 -10   1]
 [  6   3   9]]
